### ISSUE TITLE
`porter add` fails if `porter start` hasn't been run.

### ISSUE THREAD

**Issue by jessarcher** [anystack-sh/porter#1]
Hey! I love the idea of this project - great work!

I'm on Fedora Linux and when following the instructions in the README, I got the following error:

![image](https://user-images.githubusercontent.com/4977161/209590486-870b8056-7d83-4752-aa2e-867ca9b2efa4.png)

If I run `porter start` then everything works fine.

While this could just be documented, I think it would be nicer if `RestartCommand` would try to start the server if it's not currently running.

**Comment by MrMooky** [comment]
Got the same issue on latest macOS.

**Comment by PhiloNL** [comment]
Thanks @jessarcher! 😄
Added an option (https://github.com/anystack-sh/porter/pull/5) that will check if Porter is running, if it isn't, it will ask you if you want to start it.
