### ISSUE TITLE
porter can not stop or start!

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [anystack-sh/porter#13]
when I write the command: `porter stop` it is still in this situation: 

```
Stopping services: loading...
```

and when I write `porter status` I get the prompt: 
```
 Porter must be running to use this command. Do you want to start Porter? (yes/no) [yes]:
```
after I write yes, I get this

```
In SupervisordRepository.php line 120:
                                 
  Services are already running.  
                                 
```

**Comment by olumby** [comment]
Have you tried:

`rm ~/.porter/supervisord.pid`

From #8

**Comment by WatheqAlshowaiter** [comment]
thanks @olumby, it solved the problem!

I hope it will be fixed to prevent this from happening.

**Comment by PhiloNL** [comment]
Should be fixed in https://github.com/anystack-sh/porter/releases/tag/v0.0.6
