### ISSUE TITLE
Fresh Install error syntax error, unexpected token ")" in builds/porter/vendor/symfony/finder/Finder.php on line 636

### ISSUE THREAD

**Issue by Patabugen** [anystack-sh/porter#14]
I've just tried to install Porter and encountered a couple of problems. I tried it on both my laptop and desktop in case it was a system/configuration problem but I have the same problem on both.

I tried version 0.0.5 and 0.0.4 of Porter, just in case.

Desktop:
 - Ubuntu 20.0.4 (Running as WSL on Windows 10)
 - Composer 2.5.1
 - PHP: 8.0.5
Laptop:
 - Ubuntu 20.0.4 (Running as WSL on Windows 11)
 - Composer version: 2.3.5
 - PHP: 8.0.26

Installation looks good:
```bash
$ composer global require anystack-sh/porter
Changed current directory to /home/sami/.config/composer
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.0.5 for anystack-sh/porter
./composer.json has been created
Running composer update anystack-sh/porter
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking anystack-sh/porter (v0.0.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading anystack-sh/porter (v0.0.5)
  - Installing anystack-sh/porter (v0.0.5): Extracting archive
Generating autoload files
$ 
```

When I run `porter` I get a syntax error:
```bash
$ porter
PHP Parse error:  syntax error, unexpected token ")" in phar:///home/sami/.config/composer/vendor/anystack-sh/porter/builds/porter/vendor/symfony/finder/Finder.php on line 636
```

I tried adding some Vs and got a bit more info:
```bash
$ porter -vv

Box Requirements Checker
========================

> Using PHP 8.0.25
> PHP is using the following php.ini file:
  /etc/php/8.0/cli/php.ini

> Checking Box requirements:
  ..

 [OK] Your system is ready to run the application.

PHP Parse error:  syntax error, unexpected token ")" in phar:///home/sami/.config/composer/vendor/anystack-sh/porter/builds/porter/vendor/symfony/finder/Finder.php on line 636
```

**Comment by PhiloNL** [comment]
Hmm, I'm unable to replicate this on macOS; what do you get when you run `which porter`?

**Comment by trea** [comment]
The symfony/finder component at the ^6.0 constraint in this projects' composer.json would allow the current 6.2 version which requires at least PHP 8.1. Presumably the Symfony Finder file that is mentioned in the error is using newer syntax that isn't supported in 8.0.25.

**Comment by modstore** [comment]
I also got this issue when I was on php8.0, but all was good when I ran it using php8.1

**Comment by PhiloNL** [comment]
Bumped min PHP version to 8.1 https://github.com/anystack-sh/porter/pull/15
