### ISSUE TITLE
Worked for 1 day... Can't start porter anymore

### ISSUE THREAD

**Issue by Lawebso** [anystack-sh/porter#8]
Hi there,

maybe you can point me in the right direction to make porter work again.

I navigated to my directory and tried to start porter which didn't work anymore

<img width="215" alt="Screenshot 2022-12-31 at 5 06 33 AM" src="https://user-images.githubusercontent.com/106002156/210111652-d8851c1d-df61-4924-a870-7a7d42c08245.png">

Then I wanted to see the porter status

<img width="566" alt="Screenshot 2022-12-31 at 5 07 55 AM" src="https://user-images.githubusercontent.com/106002156/210111728-593e4ebd-4ceb-424d-993d-7d36644b7e9c.png">

So I thought okay - lets stop it then...

<img width="228" alt="Screenshot 2022-12-31 at 5 08 51 AM" src="https://user-images.githubusercontent.com/106002156/210111766-293a2e7b-1af5-4a0f-bd67-2ca393e2c43f.png">

But this process never finishes...

I tried to kill supervisor in the terminal as well...

uninstall & installed supervisor again using homebrew

tried to restart my Mac...

I'm using Laravel Valet and DBingin and the latest version of porter

my yml file looks like this

<img width="377" alt="Screenshot 2022-12-31 at 5 11 49 AM" src="https://user-images.githubusercontent.com/106002156/210111924-622e95d2-d248-42ad-8dca-af853f9d6d20.png">

**Comment by PhiloNL** [comment]
Hi @Lawebso,
Thanks for letting me know.

I'll look into this; for now, can you try and run the following command: 

```shell
rm ~/.porter/supervisord.pid
```

And try to start Porter again. 
Thanks!

**Comment by njoguamos** [comment]
Same error when running schedule command:

<img width="396" alt="Screenshot 2022-12-31 at 23 53 12" src="https://user-images.githubusercontent.com/29255728/210155452-5755d020-7d89-4484-9403-d2a92d182184.png">

<img width="634" alt="Screenshot 2022-12-31 at 23 52 55" src="https://user-images.githubusercontent.com/29255728/210155447-3ac67469-e23a-47a0-bbc6-883c1ebe1db6.png">


In the mean time, this is solving the problem
> 
> ```shell
> rm ~/.porter/supervisord.pid
> ```

**Comment by Lawebso** [comment]
thank you @PhiloNL 

the command solved the problem.
