### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by BenQoder** [anystack-sh/porter#9]
I can't seem to start it successfully.
It always says Fatal or Failed and there's no useful information in the log files 

![image](https://user-images.githubusercontent.com/24754078/210240333-7669dd22-c97a-4d6e-b132-e84231247453.png)

**Comment by PhiloNL** [comment]
Hi @BenQoder,
Please check `cat ~/.porter/supervisord.log` for more information.
You can also see individual logs `cat ~/.porter/logs/haayaa-app.log`.

**Comment by BenQoder** [comment]
I figured the reason why this is happening is because my command is something like

```bash
cd path/to/projects/haayaa & php artisan serve
```

The path my porter.yml file is is different from where my project is

Thus the reason why I created this pr to handle situations where we need to set custom directory.
https://github.com/anystack-sh/porter/pull/11

**Comment by dragonfire1119** [comment]
@BenQoder I had the same issue, but I ran "porter init" in each directory, then added my services and "porter add". By "porter status," you can easily examine all the services in each app.

@PhiloNL Nice work on this. I'm using it for my next.js project as well.

**Comment by BenQoder** [comment]
@dragonfire1119 your suggestion works and that's how I currently use this package.

But for situations where you need all your services for one workspace in a single porter.yml file. It will be really uneasy for projects with up to 4 or 5 service.

I hope you understand me.

**Comment by dragonfire1119** [comment]
@BenQoder I looked at how porter was constructed, and it writes to a "supervisord.conf," which sets a "directory=" and then calls the command. As a result, @PhiloNL would have to change the directory parameter to custom.

**Comment by BenQoder** [comment]
This has been fixed in v0.0.5
